### ISSUE TITLE
Constant spinner on "Transaction history" screen

### ISSUE THREAD

**Issue by filcole** [TonyHoyle/Clockwork-Highway#1]
Love, love, love the app.  Much better than the big brand equivalent.  One small glitch though.

The transaction history spinner doesn't stop spinning.  This might be because I haven't used the charging points yet, and so my history is empty?  See screenshot

![spinner hang](https://cloud.githubusercontent.com/assets/6078398/18224159/b63d80cc-71c4-11e6-9a60-f2a0dcd3c35c.png)

**Comment by TonyHoyle** [comment]
If there are no transactions never returns a result.  I've fixed it in the latest version.
